### ISSUE TITLE
Space Travelers' Hub

### ISSUE THREAD

**Issue by As1imwe-Mark** [SnakyMz/space-hub#25]
# Project Kanban Board Setup - SpaceX
In this group project, we are two people in the group i.e @SnakyMz and @As1imwe-Mark . We have successfully created the project in our repo and the link for the Group Project is below
[Space Travelers' Hub](https://github.com/SnakyMz/space-hub/projects/1)

**Comment by SnakyMz** [comment]
Made changes as suggested:
Removed the Team3 from issues.
![Screenshot 2023-08-28 220429](https://github.com/SnakyMz/space-hub/assets/115364362/63f5bb33-e1dd-4903-a0ee-c0815e96b391)
![Screenshot 2023-08-28 220516](https://github.com/SnakyMz/space-hub/assets/115364362/13bc531c-5100-4c71-92df-e3d63c9c11bc)

**Comment by frank1738** [comment]
Hi Team, 

You can go ahead with your project


<img src="https://media4.giphy.com/media/1uC8xfkZRi7Kw/giphy.gif"/>



## Highlights

✅ Tasks are assigned properly

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
